function getGraph() {
    var graph = {
        nodes: [{
            "class": 1,
            "id": 0
        }, {
            "class": 2,
            "id": 1
        }, {
            "class": 2,
            "id": 2
        }, {
            "class": 1,
            "id": 3
        }, {
            "class": 1,
            "id": 4
        }, {
            "class": 1,
            "id": 5
        }, {
            "class": 1,
            "id": 6
        }, {
            "class": 1,
            "id": 7
        }, {
            "class": 1,
            "id": 8
        }, {
            "class": 1,
            "id": 9
        }, {
            "class": 1,
            "id": 10
        }, {
            "class": 1,
            "id": 11
        }, {
            "class": 1,
            "id": 12
        }, {
            "class": 1,
            "id": 13
        }, {
            "class": 1,
            "id": 14
        }, {
            "class": 3,
            "id": 15
        }, {
            "class": 3,
            "id": 16
        }, {
            "class": 3,
            "id": 17
        }, {
            "class": 3,
            "id": 18
        }, {
            "class": 3,
            "id": 19
        }, {
            "class": 1,
            "id": 20
        }, {
            "class": 1,
            "id": 21
        }, {
            "class": 1,
            "id": 22
        }, {
            "class": 1,
            "id": 23
        }, {
            "class": 1,
            "id": 24
        }, {
            "class": 1,
            "id": 25
        }, {
            "class": 1,
            "id": 26
        }, {
            "class": 1,
            "id": 27
        }, {
            "class": 1,
            "id": 28
        }, {
            "class": 1,
            "id": 29
        }, {
            "class": 1,
            "id": 30
        }, {
            "class": 1,
            "id": 31
        }, {
            "class": 1,
            "id": 32
        }, {
            "class": 1,
            "id": 33
        }, {
            "class": 1,
            "id": 34
        }, {
            "class": 1,
            "id": 35
        }, {
            "class": 1,
            "id": 36
        }, {
            "class": 1,
            "id": 37
        }, {
            "class": 1,
            "id": 38
        }, {
            "class": 1,
            "id": 39
        }, {
            "class": 1,
            "id": 40
        }, {
            "class": 1,
            "id": 41
        }, {
            "class": 1,
            "id": 42
        }, {
            "class": 1,
            "id": 43
        }, {
            "class": 1,
            "id": 44
        }, {
            "class": 1,
            "id": 45
        }, {
            "class": 1,
            "id": 46
        }, {
            "class": 1,
            "id": 47
        }, {
            "class": 1,
            "id": 48
        }, {
            "class": 1,
            "id": 49
        }, {
            "class": 1,
            "id": 50
        }, {
            "class": 1,
            "id": 51
        }, {
            "class": 1,
            "id": 52
        }, {
            "class": 1,
            "id": 53
        }, {
            "class": 1,
            "id": 54
        }, {
            "class": 1,
            "id": 55
        }, {
            "class": 1,
            "id": 56
        }, {
            "class": 1,
            "id": 57
        }, {
            "class": 1,
            "id": 58
        }, {
            "class": 1,
            "id": 59
        }, {
            "class": 1,
            "id": 60
        }, {
            "class": 1,
            "id": 61
        }, {
            "class": 1,
            "id": 62
        }, {
            "class": 1,
            "id": 63
        }, {
            "class": 1,
            "id": 64
        }, {
            "class": 1,
            "id": 65
        }, {
            "class": 1,
            "id": 66
        }, {
            "class": 1,
            "id": 67
        }, {
            "class": 1,
            "id": 68
        }, {
            "class": 1,
            "id": 69
        }, {
            "class": 1,
            "id": 70
        }, {
            "class": 1,
            "id": 71
        }, {
            "class": 1,
            "id": 72
        }, {
            "class": 1,
            "id": 73
        }, {
            "class": 1,
            "id": 74
        }, {
            "class": 1,
            "id": 75
        }, {
            "class": 1,
            "id": 76
        }, {
            "class": 1,
            "id": 77
        }, {
            "class": 1,
            "id": 78
        }, {
            "class": 1,
            "id": 79
        }, {
            "class": 1,
            "id": 80
        }, {
            "class": 1,
            "id": 81
        }, {
            "class": 1,
            "id": 82
        }, {
            "class": 1,
            "id": 83
        }, {
            "class": 1,
            "id": 84
        }, {
            "class": 1,
            "id": 85
        }, {
            "class": 1,
            "id": 86
        }, {
            "class": 1,
            "id": 87
        }, {
            "class": 1,
            "id": 88
        }, {
            "class": 1,
            "id": 89
        }, {
            "class": 1,
            "id": 90
        }, {
            "class": 1,
            "id": 91
        }, {
            "class": 1,
            "id": 92
        }, {
            "class": 1,
            "id": 93
        }, {
            "class": 1,
            "id": 94
        }, {
            "class": 1,
            "id": 95
        }, {
            "class": 1,
            "id": 96
        }, {
            "class": 1,
            "id": 97
        }, {
            "class": 1,
            "id": 98
        }, {
            "class": 1,
            "id": 99
        }],
        links: [{
            "similarity": 0.099602,
            "source": 0,
            "target": 16,
            "id": 16
        }, {
            "similarity": 0.099396,
            "source": 0,
            "target": 67,
            "id": 67
        }, {
            "similarity": 0.099767,
            "source": 1,
            "target": 74,
            "id": 172
        }, {
            "similarity": 0.099922,
            "source": 1,
            "target": 87,
            "id": 185
        }, {
            "similarity": 0.099974,
            "source": 2,
            "target": 6,
            "id": 201
        }, {
            "similarity": 0.099679,
            "source": 3,
            "target": 29,
            "id": 320
        }, {
            "similarity": 0.099512,
            "source": 4,
            "target": 12,
            "id": 398
        }, {
            "similarity": 0.099147,
            "source": 4,
            "target": 34,
            "id": 420
        }, {
            "similarity": 0.099326,
            "source": 4,
            "target": 62,
            "id": 448
        }, {
            "similarity": 0.099153,
            "source": 4,
            "target": 94,
            "id": 480
        }, {
            "similarity": 0.099029,
            "source": 6,
            "target": 67,
            "id": 640
        }, {
            "similarity": 0.099712,
            "source": 6,
            "target": 78,
            "id": 651
        }, {
            "similarity": 0.099997,
            "source": 7,
            "target": 50,
            "id": 715
        }, {
            "similarity": 0.099937,
            "source": 9,
            "target": 42,
            "id": 888
        }, {
            "similarity": 0.099428,
            "source": 10,
            "target": 34,
            "id": 969
        }, {
            "similarity": 0.099072,
            "source": 12,
            "target": 29,
            "id": 1139
        }, {
            "similarity": 0.09984,
            "source": 12,
            "target": 70,
            "id": 1180
        }, {
            "similarity": 0.099204,
            "source": 13,
            "target": 80,
            "id": 1276
        }, {
            "similarity": 0.19311,
            "source": 15,
            "target": 16,
            "id": 1381
        }, {
            "similarity": 0.19244,
            "source": 15,
            "target": 17,
            "id": 1382
        }, {
            "similarity": 0.1994,
            "source": 15,
            "target": 18,
            "id": 1383
        }, {
            "similarity": 0.1994,
            "source": 15,
            "target": 19,
            "id": 1384
        }, {
            "similarity": 0.19343,
            "source": 16,
            "target": 17,
            "id": 1465
        }, {
            "similarity": 0.19869,
            "source": 16,
            "target": 18,
            "id": 1466
        }, {
            "similarity": 0.19869,
            "source": 16,
            "target": 19,
            "id": 1467
        }, {
            "similarity": 0.099129,
            "source": 16,
            "target": 43,
            "id": 1491
        }, {
            "similarity": 0.099465,
            "source": 16,
            "target": 53,
            "id": 1501
        }, {
            "similarity": 0.099483,
            "source": 16,
            "target": 91,
            "id": 1539
        }, {
            "similarity": 0.099739,
            "source": 16,
            "target": 92,
            "id": 1540
        }, {
            "similarity": 0.1993,
            "source": 17,
            "target": 18,
            "id": 1548
        }, {
            "similarity": 0.1993,
            "source": 17,
            "target": 19,
            "id": 1549
        }, {
            "similarity": 0.099755,
            "source": 17,
            "target": 26,
            "id": 1556
        }, {
            "similarity": 0.19244,
            "source": 18,
            "target": 19,
            "id": 1630
        }, {
            "similarity": 0.099712,
            "source": 18,
            "target": 22,
            "id": 1633
        }, {
            "similarity": 0.099799,
            "source": 18,
            "target": 23,
            "id": 1634
        }, {
            "similarity": 0.099946,
            "source": 19,
            "target": 47,
            "id": 1738
        }, {
            "similarity": 0.099708,
            "source": 19,
            "target": 60,
            "id": 1751
        }, {
            "similarity": 0.099415,
            "source": 22,
            "target": 84,
            "id": 2009
        }, {
            "similarity": 0.099844,
            "source": 23,
            "target": 45,
            "id": 2046
        }, {
            "similarity": 0.09922,
            "source": 25,
            "target": 43,
            "id": 2193
        }, {
            "similarity": 0.099659,
            "source": 25,
            "target": 66,
            "id": 2216
        }, {
            "similarity": 0.099455,
            "source": 25,
            "target": 81,
            "id": 2231
        }, {
            "similarity": 0.099127,
            "source": 26,
            "target": 67,
            "id": 2290
        }, {
            "similarity": 0.099345,
            "source": 28,
            "target": 85,
            "id": 2451
        }, {
            "similarity": 0.099308,
            "source": 30,
            "target": 49,
            "id": 2554
        }, {
            "similarity": 0.099416,
            "source": 31,
            "target": 88,
            "id": 2661
        }, {
            "similarity": 0.099997,
            "source": 32,
            "target": 95,
            "id": 2735
        }, {
            "similarity": 0.099631,
            "source": 33,
            "target": 86,
            "id": 2792
        }, {
            "similarity": 0.099195,
            "source": 34,
            "target": 78,
            "id": 2849
        }, {
            "similarity": 0.099142,
            "source": 34,
            "target": 93,
            "id": 2864
        }, {
            "similarity": 0.099602,
            "source": 37,
            "target": 48,
            "id": 3008
        }, {
            "similarity": 0.099131,
            "source": 37,
            "target": 68,
            "id": 3028
        }, {
            "similarity": 0.099496,
            "source": 37,
            "target": 91,
            "id": 3051
        }, {
            "similarity": 0.099523,
            "source": 38,
            "target": 80,
            "id": 3101
        }, {
            "similarity": 0.099362,
            "source": 41,
            "target": 57,
            "id": 3255
        }, {
            "similarity": 0.099088,
            "source": 41,
            "target": 59,
            "id": 3257
        }, {
            "similarity": 0.099957,
            "source": 44,
            "target": 85,
            "id": 3451
        }, {
            "similarity": 0.099116,
            "source": 45,
            "target": 64,
            "id": 3484
        }, {
            "similarity": 0.09955,
            "source": 46,
            "target": 63,
            "id": 3536
        }, {
            "similarity": 0.099726,
            "source": 46,
            "target": 95,
            "id": 3568
        }, {
            "similarity": 0.099917,
            "source": 47,
            "target": 68,
            "id": 3593
        }, {
            "similarity": 0.099418,
            "source": 50,
            "target": 98,
            "id": 3773
        }, {
            "similarity": 0.099814,
            "source": 51,
            "target": 70,
            "id": 3793
        }, {
            "similarity": 0.099016,
            "source": 54,
            "target": 92,
            "id": 3953
        }, {
            "similarity": 0.099073,
            "source": 55,
            "target": 94,
            "id": 3999
        }, {
            "similarity": 0.099098,
            "source": 56,
            "target": 82,
            "id": 4030
        }, {
            "similarity": 0.099024,
            "source": 58,
            "target": 97,
            "id": 4128
        }, {
            "similarity": 0.09994,
            "source": 60,
            "target": 69,
            "id": 4179
        }, {
            "similarity": 0.099772,
            "source": 61,
            "target": 76,
            "id": 4224
        }, {
            "similarity": 0.099971,
            "source": 64,
            "target": 69,
            "id": 4325
        }, {
            "similarity": 0.099932,
            "source": 69,
            "target": 96,
            "id": 4512
        }, {
            "similarity": 0.099156,
            "source": 72,
            "target": 99,
            "id": 4599
        }, {
            "similarity": 0.099817,
            "source": 73,
            "target": 87,
            "id": 4613
        }, {
            "similarity": 0.099447,
            "source": 75,
            "target": 93,
            "id": 4668
        }]
    };

    return graph;

}

function getGraph2() {
    var graph = {
        nodes: [{
            "class": 1,
            "id": 0
        }, {
            "class": 2,
            "id": 1
        }, {
            "class": 2,
            "id": 2
        }, {
            "class": 2,
            "id": 3
        }, {
            "class": 1,
            "id": 4
        }, {
            "class": 1,
            "id": 5
        }, {
            "class": 1,
            "id": 6
        }, {
            "class": 1,
            "id": 7
        }, {
            "class": 1,
            "id": 8
        }, {
            "class": 1,
            "id": 9
        }, {
            "class": 1,
            "id": 10
        }, {
            "class": 1,
            "id": 11
        }, {
            "class": 1,
            "id": 12
        }, {
            "class": 1,
            "id": 13
        }, {
            "class": 1,
            "id": 14
        }, {
            "class": 1,
            "id": 15
        }, {
            "class": 3,
            "id": 16
        }, {
            "class": 3,
            "id": 17
        }, {
            "class": 3,
            "id": 18
        }, {
            "class": 3,
            "id": 19
        }, {
            "class": 1,
            "id": 20
        }, {
            "class": 1,
            "id": 21
        }, {
            "class": 1,
            "id": 22
        }, {
            "class": 1,
            "id": 23
        }, {
            "class": 1,
            "id": 24
        }, {
            "class": 1,
            "id": 25
        }, {
            "class": 1,
            "id": 26
        }, {
            "class": 1,
            "id": 27
        }, {
            "class": 1,
            "id": 28
        }, {
            "class": 1,
            "id": 29
        }, {
            "class": 1,
            "id": 30
        }, {
            "class": 1,
            "id": 31
        }, {
            "class": 1,
            "id": 32
        }, {
            "class": 1,
            "id": 33
        }, {
            "class": 1,
            "id": 34
        }, {
            "class": 1,
            "id": 35
        }, {
            "class": 1,
            "id": 36
        }, {
            "class": 1,
            "id": 37
        }, {
            "class": 1,
            "id": 38
        }, {
            "class": 1,
            "id": 39
        }, {
            "class": 1,
            "id": 40
        }, {
            "class": 1,
            "id": 41
        }, {
            "class": 1,
            "id": 42
        }, {
            "class": 1,
            "id": 43
        }, {
            "class": 1,
            "id": 44
        }, {
            "class": 1,
            "id": 45
        }, {
            "class": 1,
            "id": 46
        }, {
            "class": 1,
            "id": 47
        }, {
            "class": 1,
            "id": 48
        }, {
            "class": 1,
            "id": 49
        }, {
            "class": 1,
            "id": 50
        }, {
            "class": 1,
            "id": 51
        }, {
            "class": 1,
            "id": 52
        }, {
            "class": 1,
            "id": 53
        }, {
            "class": 1,
            "id": 54
        }, {
            "class": 1,
            "id": 55
        }, {
            "class": 1,
            "id": 56
        }, {
            "class": 1,
            "id": 57
        }, {
            "class": 1,
            "id": 58
        }, {
            "class": 1,
            "id": 59
        }, {
            "class": 1,
            "id": 60
        }, {
            "class": 1,
            "id": 61
        }, {
            "class": 1,
            "id": 62
        }, {
            "class": 1,
            "id": 63
        }, {
            "class": 1,
            "id": 64
        }, {
            "class": 1,
            "id": 65
        }, {
            "class": 1,
            "id": 66
        }, {
            "class": 1,
            "id": 67
        }, {
            "class": 1,
            "id": 68
        }, {
            "class": 1,
            "id": 69
        }, {
            "class": 1,
            "id": 70
        }, {
            "class": 1,
            "id": 71
        }, {
            "class": 1,
            "id": 72
        }, {
            "class": 1,
            "id": 73
        }, {
            "class": 1,
            "id": 74
        }, {
            "class": 1,
            "id": 75
        }, {
            "class": 1,
            "id": 76
        }, {
            "class": 1,
            "id": 77
        }, {
            "class": 1,
            "id": 78
        }, {
            "class": 1,
            "id": 79
        }, {
            "class": 1,
            "id": 80
        }, {
            "class": 1,
            "id": 81
        }, {
            "class": 1,
            "id": 82
        }, {
            "class": 1,
            "id": 83
        }, {
            "class": 1,
            "id": 84
        }, {
            "class": 1,
            "id": 85
        }, {
            "class": 1,
            "id": 86
        }, {
            "class": 1,
            "id": 87
        }, {
            "class": 1,
            "id": 88
        }, {
            "class": 1,
            "id": 89
        }, {
            "class": 1,
            "id": 90
        }, {
            "class": 1,
            "id": 91
        }, {
            "class": 1,
            "id": 92
        }, {
            "class": 1,
            "id": 93
        }, {
            "class": 1,
            "id": 94
        }, {
            "class": 1,
            "id": 95
        }, {
            "class": 1,
            "id": 96
        }, {
            "class": 1,
            "id": 97
        }, {
            "class": 1,
            "id": 98
        }, {
            "class": 1,
            "id": 99
        }],
        links: [{
            "similarity": 0.099602,
            "source": 0,
            "target": 16,
            "id": 16
        }, {
            "similarity": 0.099396,
            "source": 0,
            "target": 67,
            "id": 67
        }, {
            "similarity": 0.099767,
            "source": 1,
            "target": 74,
            "id": 172
        }, {
            "similarity": 0.099922,
            "source": 1,
            "target": 87,
            "id": 185
        }, {
            "similarity": 0.099974,
            "source": 2,
            "target": 6,
            "id": 201
        }, {
            "similarity": 0.099679,
            "source": 3,
            "target": 29,
            "id": 320
        }, {
            "similarity": 0.099512,
            "source": 4,
            "target": 12,
            "id": 398
        }, {
            "similarity": 0.099147,
            "source": 4,
            "target": 34,
            "id": 420
        }, {
            "similarity": 0.099326,
            "source": 4,
            "target": 62,
            "id": 448
        }, {
            "similarity": 0.099153,
            "source": 4,
            "target": 94,
            "id": 480
        }, {
            "similarity": 0.099029,
            "source": 6,
            "target": 67,
            "id": 640
        }, {
            "similarity": 0.099712,
            "source": 6,
            "target": 78,
            "id": 651
        }, {
            "similarity": 0.099997,
            "source": 7,
            "target": 50,
            "id": 715
        }, {
            "similarity": 0.099937,
            "source": 9,
            "target": 42,
            "id": 888
        }, {
            "similarity": 0.099428,
            "source": 10,
            "target": 34,
            "id": 969
        }, {
            "similarity": 0.099072,
            "source": 12,
            "target": 29,
            "id": 1139
        }, {
            "similarity": 0.09984,
            "source": 12,
            "target": 70,
            "id": 1180
        }, {
            "similarity": 0.099204,
            "source": 13,
            "target": 80,
            "id": 1276
        }, {
            "similarity": 0.19343,
            "source": 16,
            "target": 17,
            "id": 1465
        }, {
            "similarity": 0.19869,
            "source": 16,
            "target": 18,
            "id": 1466
        }, {
            "similarity": 0.19869,
            "source": 16,
            "target": 19,
            "id": 1467
        }, {
            "similarity": 0.099129,
            "source": 16,
            "target": 43,
            "id": 1491
        }, {
            "similarity": 0.099465,
            "source": 16,
            "target": 53,
            "id": 1501
        }, {
            "similarity": 0.099483,
            "source": 16,
            "target": 91,
            "id": 1539
        }, {
            "similarity": 0.099739,
            "source": 16,
            "target": 92,
            "id": 1540
        }, {
            "similarity": 0.1993,
            "source": 17,
            "target": 18,
            "id": 1548
        }, {
            "similarity": 0.1993,
            "source": 17,
            "target": 19,
            "id": 1549
        }, {
            "similarity": 0.099755,
            "source": 17,
            "target": 26,
            "id": 1556
        }, {
            "similarity": 0.19244,
            "source": 18,
            "target": 19,
            "id": 1630
        }, {
            "similarity": 0.099712,
            "source": 18,
            "target": 22,
            "id": 1633
        }, {
            "similarity": 0.099799,
            "source": 18,
            "target": 23,
            "id": 1634
        }, {
            "similarity": 0.099946,
            "source": 19,
            "target": 47,
            "id": 1738
        }, {
            "similarity": 0.099708,
            "source": 19,
            "target": 60,
            "id": 1751
        }, {
            "similarity": 0.099415,
            "source": 22,
            "target": 84,
            "id": 2009
        }, {
            "similarity": 0.099844,
            "source": 23,
            "target": 45,
            "id": 2046
        }, {
            "similarity": 0.09922,
            "source": 25,
            "target": 43,
            "id": 2193
        }, {
            "similarity": 0.099659,
            "source": 25,
            "target": 66,
            "id": 2216
        }, {
            "similarity": 0.099455,
            "source": 25,
            "target": 81,
            "id": 2231
        }, {
            "similarity": 0.099127,
            "source": 26,
            "target": 67,
            "id": 2290
        }, {
            "similarity": 0.099345,
            "source": 28,
            "target": 85,
            "id": 2451
        }, {
            "similarity": 0.099308,
            "source": 30,
            "target": 49,
            "id": 2554
        }, {
            "similarity": 0.099416,
            "source": 31,
            "target": 88,
            "id": 2661
        }, {
            "similarity": 0.099997,
            "source": 32,
            "target": 95,
            "id": 2735
        }, {
            "similarity": 0.099631,
            "source": 33,
            "target": 86,
            "id": 2792
        }, {
            "similarity": 0.099195,
            "source": 34,
            "target": 78,
            "id": 2849
        }, {
            "similarity": 0.099142,
            "source": 34,
            "target": 93,
            "id": 2864
        }, {
            "similarity": 0.099602,
            "source": 37,
            "target": 48,
            "id": 3008
        }, {
            "similarity": 0.099131,
            "source": 37,
            "target": 68,
            "id": 3028
        }, {
            "similarity": 0.099496,
            "source": 37,
            "target": 91,
            "id": 3051
        }, {
            "similarity": 0.099523,
            "source": 38,
            "target": 80,
            "id": 3101
        }, {
            "similarity": 0.099362,
            "source": 41,
            "target": 57,
            "id": 3255
        }, {
            "similarity": 0.099088,
            "source": 41,
            "target": 59,
            "id": 3257
        }, {
            "similarity": 0.099957,
            "source": 44,
            "target": 85,
            "id": 3451
        }, {
            "similarity": 0.099116,
            "source": 45,
            "target": 64,
            "id": 3484
        }, {
            "similarity": 0.09955,
            "source": 46,
            "target": 63,
            "id": 3536
        }, {
            "similarity": 0.099726,
            "source": 46,
            "target": 95,
            "id": 3568
        }, {
            "similarity": 0.099917,
            "source": 47,
            "target": 68,
            "id": 3593
        }, {
            "similarity": 0.099418,
            "source": 50,
            "target": 98,
            "id": 3773
        }, {
            "similarity": 0.099814,
            "source": 51,
            "target": 70,
            "id": 3793
        }, {
            "similarity": 0.099016,
            "source": 54,
            "target": 92,
            "id": 3953
        }, {
            "similarity": 0.099073,
            "source": 55,
            "target": 94,
            "id": 3999
        }, {
            "similarity": 0.099098,
            "source": 56,
            "target": 82,
            "id": 4030
        }, {
            "similarity": 0.099024,
            "source": 58,
            "target": 97,
            "id": 4128
        }, {
            "similarity": 0.09994,
            "source": 60,
            "target": 69,
            "id": 4179
        }, {
            "similarity": 0.099772,
            "source": 61,
            "target": 76,
            "id": 4224
        }, {
            "similarity": 0.099971,
            "source": 64,
            "target": 69,
            "id": 4325
        }, {
            "similarity": 0.099932,
            "source": 69,
            "target": 96,
            "id": 4512
        }, {
            "similarity": 0.099156,
            "source": 72,
            "target": 99,
            "id": 4599
        }, {
            "similarity": 0.099817,
            "source": 73,
            "target": 87,
            "id": 4613
        }, {
            "similarity": 0.099447,
            "source": 75,
            "target": 93,
            "id": 4668
        }]
    };

    return graph;
}
var graph = getGraph();
var width = 1200;
var height = 900;
var radius = 10;
var svg = d3.select('#chartArea').append('svg');
svg.attr('height', height + 'px')
    .attr('width', width + 'px')
    .style('pointer-events', 'all');

function g10(n) {
    var g10Colors = ["#3366cc", "#dc3912", "#ff9900", "#109618", "#990099", "#0099c6", "#dd4477", "#66aa00", "#b82e2e", "#316395", "#994499", "#22aa99", "#aaaa11", "#6633cc", "#e67300", "#8b0707", "#651067", "#329262", "#5574a6", "#3b3eac"];
    return g10Colors[n % g10Colors.length];
}

var force = d3.layout.force()
    .nodes(graph.nodes)
    .links(graph.links)
    .size([width, height])
    .linkDistance([50])
    .charge([-200])
    .start();

var links = svg.selectAll('.link')
    .data(graph.links, function(d) {
        return d.id;
    })
    .enter()
    .append('line')
    .attr('class', 'link');

var nodes = svg.selectAll('.node')
    .data(graph.nodes, function(d) {
        return d.id;
    })
    .enter()
    .append('circle')
    .attr('class', 'node')
    .attr('cx', function(d) {
        return d.x;
    })
    .attr('cy', function(d) {
        return d.y;
    })
    .attr('r', radius)
    .attr('fill', function(d) {
        return g10(d.class - 1);
    })
    .call(force.drag);


force.on('tick', function() {
    nodes.attr('cx', function(d) {
            return d.x;
        })
        .attr('cy', function(d) {
            return d.y;
        });

    links.attr('x1', function(d) {
            return d.source.x;
        })
        .attr('y1', function(d) {
            return d.source.y;
        })
        .attr('x2', function(d) {
            return d.target.x;
        })
        .attr('y2', function(d) {
            return d.target.y;
        });
});

var linkIndex = {};

graph.links.forEach(function(d) {
    linkIndex[d.source.id + '-' + d.target.id] = true;
});

var transitionDuration = 1000;

nodes.on('mouseover', function(d) {

    nodes.classed('node-active', function(o) {
        return linkIndex[o.id + '-' + d.id] || linkIndex[d.id + '-' + o.id];
    });

    d3.select(this)
        .classed('node-active', true);

    links.classed('link-active', function(o) {
        return o.source == d || o.target == d;
    });

    d3.select(this)
        .transition()
        .duration(transitionDuration)
        .attr('r', radius + 5)
        .attr('fill', '#999999');

});

nodes.on('mouseout', function() {

    nodes.classed('node-active', false);
    links.classed('link-active', false);

    d3.select(this)
        .transition()
        .duration(transitionDuration)
        .attr('r', radius)
        .attr('fill', function(d) {
            return g10(d.class - 1);
        });
});


/*iteration 2 transitions */
setTimeout(function(){
  console.log('iteration 2 started');
  graph = getGraph2();
  // force.nodes(graph2.nodes)
  //     .links(graph2.links)
  //     .start();
  //i don't think there will be any changes in the nodes (maybe for the labels)
  nodes = svg.selectAll('.node')
      .data(force.nodes(), function(d) {
          return d.id;
      })
      .transition()
      .delay(2 * transitionDuration)
      .duration(transitionDuration)
      .attr('cx', function(d) {
          return d.x;
      })
      .attr('cy', function(d) {
          return d.y;
      })
      .attr('fill', function(d) {
          return g10(d.class - 1);
      });

  // links = svg.selectAll('.link')
  //     .data(force.links(), function(d) {
  //         return d.id;
  //     })
  //     .exit()
  //     .remove();

      force.start();

}, 5000);
